### ISSUE TITLE
Isolating apps by using subinterpreters

### ISSUE THREAD

**Issue by mliezun** [mliezun/caddy-snake#10]
Run each app on a separate subinterpreter, that will make them isolated from each other.

Since Python 3.12, subinterpreters can have their own GIL. That will also make the faster and more resource efficient.

As of now, there's a draft PR #9. While working on it I found a bug that doesn't allow to successfully use subinterpreters in Python 3.12 or later. I filed an issue on the CPython project https://github.com/python/cpython/issues/117482

Overall subinterpreters don't seem stable and I think they still need some improvements in future Python versions to make them usable.

**Comment by mliezun** [comment]
The current open PR #9 implements subinterpreters. While testing an implementation for ASGI I found that PyO3 doesn't yet support subinterpreters. So Im putting this on hold for now.

See an example error while trying to run FastAPI:

```
Traceback (most recent call last):
  File "/Users/mliezun/Projects/github/caddy-snake/tests/fastapi/main.py", line 5, in <module>
    from fastapi import FastAPI, UploadFile
  File "/Users/mliezun/Projects/github/caddy-snake/tests/fastapi/venv/lib/python3.13/site-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/Users/mliezun/Projects/github/caddy-snake/tests/fastapi/venv/lib/python3.13/site-packages/fastapi/applications.py", line 16, in <module>
    from fastapi import routing
  File "/Users/mliezun/Projects/github/caddy-snake/tests/fastapi/venv/lib/python3.13/site-packages/fastapi/routing.py", line 24, in <module>
    from fastapi import params
  File "/Users/mliezun/Projects/github/caddy-snake/tests/fastapi/venv/lib/python3.13/site-packages/fastapi/params.py", line 5, in <module>
    from fastapi.openapi.models import Example
  File "/Users/mliezun/Projects/github/caddy-snake/tests/fastapi/venv/lib/python3.13/site-packages/fastapi/openapi/models.py", line 4, in <module>
    from fastapi._compat import (
    ...<6 lines>...
    )
  File "/Users/mliezun/Projects/github/caddy-snake/tests/fastapi/venv/lib/python3.13/site-packages/fastapi/_compat.py", line 21, in <module>
    from fastapi.exceptions import RequestErrorModel
  File "/Users/mliezun/Projects/github/caddy-snake/tests/fastapi/venv/lib/python3.13/site-packages/fastapi/exceptions.py", line 3, in <module>
    from pydantic import BaseModel, create_model
  File "/Users/mliezun/Projects/github/caddy-snake/tests/fastapi/venv/lib/python3.13/site-packages/pydantic/__init__.py", line 418, in __getattr__
    module = import_module(module_name, package=package)
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mliezun/Projects/github/caddy-snake/tests/fastapi/venv/lib/python3.13/site-packages/pydantic/main.py", line 29, in <module>
    import pydantic_core
  File "/Users/mliezun/Projects/github/caddy-snake/tests/fastapi/venv/lib/python3.13/site-packages/pydantic_core/__init__.py", line 6, in <module>
    from ._pydantic_core import (
    ...<22 lines>...
    )
ImportError: PyO3 modules do not yet support subinterpreters, see https://github.com/PyO3/pyo3/issues/576
```
