### ISSUE TITLE
Is it possible to include the Python interpreter in the caddy static binary? 

### ISSUE THREAD

**Issue by nickchomey** [mliezun/caddy-snake#7]
Frankenphp allows for including php in the single caddy go binary https://frankenphp.dev/docs/static/

Is something like this possible with Python so that an application could be deployed on a system without Python installed without using docker?

**Comment by mliezun** [comment]
Hi @nickchomey!

It's possible to statically link Python with this Caddy plugin, I tested it by building it with this Dockerfile:

```Dockerfile
FROM alpine:latest

WORKDIR /root

RUN apk update &&\
    apk add python3-dev go &&\
    go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest &&\
    CGO_ENABLED=1 CGO_LDFLAGS="-L/usr/lib/python3.11/config-3.11-x86_64-linux-musl -static-pie" \
    XCADDY_GO_BUILD_FLAGS="-buildmode=pie -tags 'cgo netgo osusergo static_build' -ldflags \"-linkmode=external\"" \
    /root/go/bin/xcaddy build --with github.com/mliezun/caddy-snake
```

The resulting binary would be found in `/root/caddy`.

But the problem is that if you copy that binary into a different system. You'll get an error like this:

```shell
$ ./caddy-static
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'caddysnake'
  isolated = 0
  environment = 1
  user site = 1
  safe_path = 0
  import site = 1
  is in build tree = 0
  stdlib dir = '/usr/lib/python3.11'
  sys._base_executable = ''
  sys.base_prefix = '/usr'
  sys.base_exec_prefix = '/usr'
  sys.platlibdir = 'lib'
  sys.executable = ''
  sys.prefix = '/usr'
  sys.exec_prefix = '/usr'
  sys.path = [
    '/usr/lib/python311.zip',
    '/usr/lib/python3.11',
    '/usr/lib/python3.11/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007eff36099740 (most recent call first):
  <no Python frame>
``` 

This is because even if we have the full python interpreter inside the final binary, the python stdlib is shipped separately.

There's a possible solution were we could work around this issue by shipping the caddy+plugin binary and a `.zip` file that has the stdlib, but it's not trivial to implement.

May I ask, why are you interested in this solution? Maybe I can offer some other alternatives.

**Comment by mliezun** [comment]
Thank you for filing the issue!

I also like the idea of being able to ship as a single binary. Plus, it's useful if you have access to a server to write files but not to install system packages.

I'd like to add this feature, just don't know what's the best way to do it at the moment

**Comment by mliezun** [comment]
I tested something equivalent to what those AIs are suggesting. Copy the contents of the python-stdlib (`/usr/lib/python3.11`) into a `.tar.gz` file and then decompress it in the target system.

It works half-way, you can actually get to execute some python code, but if you load any python package that is provided as a `.so` (all files under `/usr/lib/python3.11/lib-dynload`) instead of a `.py` you get an error. For example, the `md5` function would be unusable in that case, you would get an error like:

```
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/lib/python3.11/hashlib.py", line 307, in <module>
    globals()[__func_name] = __get_hash(__func_name)
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
Traceback (most recent call last):
  File "/root/simple_app.py", line 2, in <module>
    from hashlib import md5
ImportError: cannot import name 'md5' from 'hashlib' (/usr/lib/python3.11/hashlib.py)
```

I have two ideas on how to circumvent the problem:
- Build python statically from source following this guide: [https://wiki.python.org/moin/BuildStatically](https://wiki.python.org/moin/BuildStatically), and try to use the stdlib resulting from that instead of the one provided by the system packages. Maybe that will be enough.
- Look into how [PyInstaller](https://github.com/pyinstaller/pyinstaller) ships the stdlib and try to mimic it.

**Comment by mliezun** [comment]
There's an archived project that implements the stdlib in pure-python: https://github.com/beeware/ouroboros

Some other initiative like that would also be useful.

**Comment by mliezun** [comment]
It might be worth looking into: https://github.com/indygreg/python-build-standalone

**Comment by mliezun** [comment]
That all seems cool!

I tested with pyinstaller, you can generate a folder with the needed files with this command `pyinstaller -d noarchive main.py`. Where the Python file is the one that you will use as your entrypoint for caddy.

Then changed the init code here https://github.com/mliezun/caddy-snake/blob/main/caddysnake.c#L382, by adding the following lines:

```C
  config.module_search_paths_set = 1;
  config.site_import = 0;
  wchar_t *paths[] = {
      L"/path/to/folder/base_library.zip",
      L"/path/to/folder/lib-dynload",
      L"/path/to/folder/"};
  int num_paths = sizeof(paths) / sizeof(paths[0]);
  // Set the module search paths
  status = PyConfig_SetWideStringList(&config, &config.module_search_paths,
                                      num_paths, paths);
  if (PyStatus_Exception(status)) {
    goto exception;
  }
```

That changes the `sys.path` to make sure it's loading from the folder generated by pyinstaller. Luckily it worked fine this time and I was able to caddy with the plugin.

Going one step further would be embedding that folder with `fs.Embed` and extracting into a temporary folder, then using the path from the temp folder in C to load the correct libraries.

I'm not sure if I want to integrate this into the plugin in it's current state. I think it would make more sense when it's more mature and the interface for creating static binaries is better defined.

**Comment by mliezun** [comment]
Cool!

I think I would prefer the plugin to work similarly to python standalone builds. In which the libraries are linked together with the final binary.

But if you want to produce a single binary now, the above instructions should work. Also, make sure your project imports packages: queue, threading. Otherwise pyinstaller will not bundle them and they're needed internally by caddy-snake.

**Comment by mliezun** [comment]
Of course! Thank you for your interest and collaboration sorting this out 😉

**Comment by mliezun** [comment]
I think Rye works at a different stage, we're looking for something that will let us produce a single binary, and Rye is trying to bundle a bunch of different tools for project management in one place. It's still an awesome tool and we should definitely support projects that use it. But it's not related to static binaries as far as I can tell.

**Comment by mliezun** [comment]
We're on the same page about being able to produce a single binary with caddy and any plugins you want inside.

But AFAIK Rye is just copying the python standalone binary and using some tools around it. It doesn't compile or do anything else.

What we need to do is to setup a build process similar to what python standalone does and integrate it with go and caddy.

**Comment by mliezun** [comment]
> As such, cant either of them simply be Go Embedded in Caddy Snake?

With Go embed you can embed any file you want inside the final binary. Whether that's something we want or not in this case is up for discussion.

> Is there anything about that that isn't clear or seems fundamentally incorrect? Maybe I still just misunderstand how Caddy Snake works?!

We're not bundling the Python executable/binary inside Caddy. What we're doing is linking the resulting binary so that it loads `libpython.so` on runtime and can call Python code/functions directly from Caddy, without needing to start a new process. All occurs within the same unique OS-level process.

My take is that I don't know at this point what the "correct" way of generating single binaries should be. And I think there's still a lot of work to do in this plugin before we get to that point.

**Comment by mliezun** [comment]
That's awesome! Definitely worth a look. 

We could add a `worker` mode in which we use pyodide to run apps. The user could then select to run in "normal" or "worker" mode using a config in Caddyfile.

I think we still should let everyone use standard Python for maximum compatibility.

**Comment by mliezun** [comment]
That just downloads the full python binary. It doesn't apply to our case

**Comment by mliezun** [comment]
No worries! Is good to hear some ideas 👌

**Comment by codablock** [comment]
Hello :) I'm the maintainer of the mentioned go-embed-python project and I'm searching for mentions of it from time to time and found this issue. Just wanted to clarify that go-embed-python is downloading the Python binary at the time of package release and actually committing it to the release tag. This means, the binaries + Python libraries are fully embedded if you add go-embed-python as a dependency.

**Comment by mliezun** [comment]
I found this project, I think it could be useful to building a single binary.

https://github.com/NilsIrl/dockerc
